name: flutter_hybrid_starter
description: "A Flutter starter template with Hybrid Architecture, MVVM, and Riverpod."
version: 1.0.0
homepage: https://github.com/yourusername/flutter_hybrid_starter
repository: https://github.com/yourusername/flutter_hybrid_starter
license: MIT

environment:
  sdk: '>=3.3.4 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg